apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  volumes:
  - name: default-volume
    persistentVolumeClaim:
      #claimName: default-pvc           #works
      #claimName: default-rwm-pvc       #issue: default sc doesn't support MULTI_NODE_MULTI_WRITER
      #claimName: aws-ebs-csi-multi-pvc #issue: new sc doesn't support MULTI_NODE_MULTI_WRITER
      #claimName: aws-ebs-multi-pvc     #issue: new sc doesn't support MULTI_NODE_MULTI_WRITER
      #claimName: aws-efs-multi-pvc     #issue: no AWS EFS
      #claimName: nfs-pvc
      claimName: nfs-s3-pvc
  containers:
  - image: busybox
    command:
      - sleep
      - "300"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
      - name: default-volume
        mountPath: /data
        readOnly: false
  restartPolicy: Always