kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kyma-nfs-sc
provisioner: kubernetes.io/fake-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: kyma-nfs-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    #- ReadWriteOnce
  nfs:
    #server: nfs-server.dev.svc.cluster.local
    #server: nfs-server.default.svc.cluster.local
    #on AWS  clusterip seems to work
    server: 100.66.61.236
    path: "/"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  #finailzer specification seemed to be needed to help deleting pvc
  finalizers: null
spec:
  #storageClassName: ""
  storageClassName: kyma-nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi