kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kyma-nfs-sc
provisioner: kubernetes.io/fake-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: kyma-nfs-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    #- ReadWriteOnce
  #nfs:
  #   path: <insert/path/to/share>
  #   server: <insert_nfs_server_ip_or_name>
  nfs:
    #server: nfs-server.dev.svc.cluster.local
    #server: nfs-server.default.svc.cluster.local
    #on AWS  clusterip seems to work
    server: 100.70.87.144
    path: "/"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  #storageClassName: ""
  storageClassName: kyma-nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi