apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs-csi-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-ebs-csi-pvc
spec:
  storageClassName: aws-ebs-csi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi