#https://stackoverflow.com/questions/51212904/kubernetes-pvc-with-readwritemany-on-aws
# EFS slower than glusterfs .. to be verified
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-efs-pv
spec:
  storageClassName: aws-efs-sc
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi # Doesn't really matter, as EFS does not enforce it anyway
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07d4da06ca18b0d6f 
    #AttachVolume.Attach failed for volume "aws-efs-pv" : attachdetachment timeout for volume fs-07d4da06ca18b0d6f
                  ###fs-642da695   ## don't know with BTP Kyma service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-efs-multi-pvc
  #labels:
  #  app: aws-efs-pv
spec:
  storageClassName: aws-efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi