apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
  #labels:
  #  demo: nfs-pv-provisioning
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi