apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs-multi-sc
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: "io2"
  #multiattachenabled: "true"  #paraemter not recognised
  iopsPerGb: "10"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-ebs-multi-pvc
spec:
  storageClassName: aws-ebs-multi-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi